apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-react-deployment
  namespace: hello-react
  labels:
    app: hello-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-react
  template:
    metadata:
      labels:
        app: hello-react
    spec:
      containers:
      - name: hello-react
        image: jonasb8/hello-react
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-react
  namespace: hello-react
spec:
  selector:
    app: hello-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-staging
  name: hello-react-ingress
  namespace: hello-react
spec:
  ingressClassName: nginx
  rules:
  - host: 123.hello-react.162.19.17.95.nip.io
    http:
      paths:
      - backend:
          service:
            name: hello-react # nom du service à exposer
            port:
              number: 80 # doit matcher le port du service hello-react
        path: /
        pathType: Prefix
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - 123.hello-react.162.19.17.95.nip.io
    secretName: myingress-cert